// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/legitahmad/logithm-backend/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/legitahmad/logithm-backend/ent/course"
	"github.com/legitahmad/logithm-backend/ent/coursemembership"
	"github.com/legitahmad/logithm-backend/ent/refreshsession"
	"github.com/legitahmad/logithm-backend/ent/teacherinvitation"
	"github.com/legitahmad/logithm-backend/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Course is the client for interacting with the Course builders.
	Course *CourseClient
	// CourseMembership is the client for interacting with the CourseMembership builders.
	CourseMembership *CourseMembershipClient
	// RefreshSession is the client for interacting with the RefreshSession builders.
	RefreshSession *RefreshSessionClient
	// TeacherInvitation is the client for interacting with the TeacherInvitation builders.
	TeacherInvitation *TeacherInvitationClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Course = NewCourseClient(c.config)
	c.CourseMembership = NewCourseMembershipClient(c.config)
	c.RefreshSession = NewRefreshSessionClient(c.config)
	c.TeacherInvitation = NewTeacherInvitationClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		Course:            NewCourseClient(cfg),
		CourseMembership:  NewCourseMembershipClient(cfg),
		RefreshSession:    NewRefreshSessionClient(cfg),
		TeacherInvitation: NewTeacherInvitationClient(cfg),
		User:              NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		Course:            NewCourseClient(cfg),
		CourseMembership:  NewCourseMembershipClient(cfg),
		RefreshSession:    NewRefreshSessionClient(cfg),
		TeacherInvitation: NewTeacherInvitationClient(cfg),
		User:              NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Course.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Course.Use(hooks...)
	c.CourseMembership.Use(hooks...)
	c.RefreshSession.Use(hooks...)
	c.TeacherInvitation.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Course.Intercept(interceptors...)
	c.CourseMembership.Intercept(interceptors...)
	c.RefreshSession.Intercept(interceptors...)
	c.TeacherInvitation.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CourseMutation:
		return c.Course.mutate(ctx, m)
	case *CourseMembershipMutation:
		return c.CourseMembership.mutate(ctx, m)
	case *RefreshSessionMutation:
		return c.RefreshSession.mutate(ctx, m)
	case *TeacherInvitationMutation:
		return c.TeacherInvitation.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CourseClient is a client for the Course schema.
type CourseClient struct {
	config
}

// NewCourseClient returns a client for the Course from the given config.
func NewCourseClient(c config) *CourseClient {
	return &CourseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `course.Hooks(f(g(h())))`.
func (c *CourseClient) Use(hooks ...Hook) {
	c.hooks.Course = append(c.hooks.Course, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `course.Intercept(f(g(h())))`.
func (c *CourseClient) Intercept(interceptors ...Interceptor) {
	c.inters.Course = append(c.inters.Course, interceptors...)
}

// Create returns a builder for creating a Course entity.
func (c *CourseClient) Create() *CourseCreate {
	mutation := newCourseMutation(c.config, OpCreate)
	return &CourseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Course entities.
func (c *CourseClient) CreateBulk(builders ...*CourseCreate) *CourseCreateBulk {
	return &CourseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CourseClient) MapCreateBulk(slice any, setFunc func(*CourseCreate, int)) *CourseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CourseCreateBulk{err: fmt.Errorf("calling to CourseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CourseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CourseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Course.
func (c *CourseClient) Update() *CourseUpdate {
	mutation := newCourseMutation(c.config, OpUpdate)
	return &CourseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseClient) UpdateOne(_m *Course) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourse(_m))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseClient) UpdateOneID(id int) *CourseUpdateOne {
	mutation := newCourseMutation(c.config, OpUpdateOne, withCourseID(id))
	return &CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Course.
func (c *CourseClient) Delete() *CourseDelete {
	mutation := newCourseMutation(c.config, OpDelete)
	return &CourseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseClient) DeleteOne(_m *Course) *CourseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CourseClient) DeleteOneID(id int) *CourseDeleteOne {
	builder := c.Delete().Where(course.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseDeleteOne{builder}
}

// Query returns a query builder for Course.
func (c *CourseClient) Query() *CourseQuery {
	return &CourseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCourse},
		inters: c.Interceptors(),
	}
}

// Get returns a Course entity by its id.
func (c *CourseClient) Get(ctx context.Context, id int) (*Course, error) {
	return c.Query().Where(course.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseClient) GetX(ctx context.Context, id int) *Course {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a Course.
func (c *CourseClient) QueryOwner(_m *Course) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, course.OwnerTable, course.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMemberships queries the memberships edge of a Course.
func (c *CourseClient) QueryMemberships(_m *Course) *CourseMembershipQuery {
	query := (&CourseMembershipClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(coursemembership.Table, coursemembership.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.MembershipsTable, course.MembershipsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTeacherInvitations queries the teacher_invitations edge of a Course.
func (c *CourseClient) QueryTeacherInvitations(_m *Course) *TeacherInvitationQuery {
	query := (&TeacherInvitationClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(course.Table, course.FieldID, id),
			sqlgraph.To(teacherinvitation.Table, teacherinvitation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, course.TeacherInvitationsTable, course.TeacherInvitationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CourseClient) Hooks() []Hook {
	return c.hooks.Course
}

// Interceptors returns the client interceptors.
func (c *CourseClient) Interceptors() []Interceptor {
	return c.inters.Course
}

func (c *CourseClient) mutate(ctx context.Context, m *CourseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CourseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CourseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CourseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CourseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Course mutation op: %q", m.Op())
	}
}

// CourseMembershipClient is a client for the CourseMembership schema.
type CourseMembershipClient struct {
	config
}

// NewCourseMembershipClient returns a client for the CourseMembership from the given config.
func NewCourseMembershipClient(c config) *CourseMembershipClient {
	return &CourseMembershipClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `coursemembership.Hooks(f(g(h())))`.
func (c *CourseMembershipClient) Use(hooks ...Hook) {
	c.hooks.CourseMembership = append(c.hooks.CourseMembership, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `coursemembership.Intercept(f(g(h())))`.
func (c *CourseMembershipClient) Intercept(interceptors ...Interceptor) {
	c.inters.CourseMembership = append(c.inters.CourseMembership, interceptors...)
}

// Create returns a builder for creating a CourseMembership entity.
func (c *CourseMembershipClient) Create() *CourseMembershipCreate {
	mutation := newCourseMembershipMutation(c.config, OpCreate)
	return &CourseMembershipCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CourseMembership entities.
func (c *CourseMembershipClient) CreateBulk(builders ...*CourseMembershipCreate) *CourseMembershipCreateBulk {
	return &CourseMembershipCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CourseMembershipClient) MapCreateBulk(slice any, setFunc func(*CourseMembershipCreate, int)) *CourseMembershipCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CourseMembershipCreateBulk{err: fmt.Errorf("calling to CourseMembershipClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CourseMembershipCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CourseMembershipCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CourseMembership.
func (c *CourseMembershipClient) Update() *CourseMembershipUpdate {
	mutation := newCourseMembershipMutation(c.config, OpUpdate)
	return &CourseMembershipUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CourseMembershipClient) UpdateOne(_m *CourseMembership) *CourseMembershipUpdateOne {
	mutation := newCourseMembershipMutation(c.config, OpUpdateOne, withCourseMembership(_m))
	return &CourseMembershipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CourseMembershipClient) UpdateOneID(id int) *CourseMembershipUpdateOne {
	mutation := newCourseMembershipMutation(c.config, OpUpdateOne, withCourseMembershipID(id))
	return &CourseMembershipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CourseMembership.
func (c *CourseMembershipClient) Delete() *CourseMembershipDelete {
	mutation := newCourseMembershipMutation(c.config, OpDelete)
	return &CourseMembershipDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CourseMembershipClient) DeleteOne(_m *CourseMembership) *CourseMembershipDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CourseMembershipClient) DeleteOneID(id int) *CourseMembershipDeleteOne {
	builder := c.Delete().Where(coursemembership.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CourseMembershipDeleteOne{builder}
}

// Query returns a query builder for CourseMembership.
func (c *CourseMembershipClient) Query() *CourseMembershipQuery {
	return &CourseMembershipQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCourseMembership},
		inters: c.Interceptors(),
	}
}

// Get returns a CourseMembership entity by its id.
func (c *CourseMembershipClient) Get(ctx context.Context, id int) (*CourseMembership, error) {
	return c.Query().Where(coursemembership.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CourseMembershipClient) GetX(ctx context.Context, id int) *CourseMembership {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a CourseMembership.
func (c *CourseMembershipClient) QueryUser(_m *CourseMembership) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(coursemembership.Table, coursemembership.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, coursemembership.UserTable, coursemembership.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCourse queries the course edge of a CourseMembership.
func (c *CourseMembershipClient) QueryCourse(_m *CourseMembership) *CourseQuery {
	query := (&CourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(coursemembership.Table, coursemembership.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, coursemembership.CourseTable, coursemembership.CourseColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CourseMembershipClient) Hooks() []Hook {
	return c.hooks.CourseMembership
}

// Interceptors returns the client interceptors.
func (c *CourseMembershipClient) Interceptors() []Interceptor {
	return c.inters.CourseMembership
}

func (c *CourseMembershipClient) mutate(ctx context.Context, m *CourseMembershipMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CourseMembershipCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CourseMembershipUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CourseMembershipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CourseMembershipDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CourseMembership mutation op: %q", m.Op())
	}
}

// RefreshSessionClient is a client for the RefreshSession schema.
type RefreshSessionClient struct {
	config
}

// NewRefreshSessionClient returns a client for the RefreshSession from the given config.
func NewRefreshSessionClient(c config) *RefreshSessionClient {
	return &RefreshSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `refreshsession.Hooks(f(g(h())))`.
func (c *RefreshSessionClient) Use(hooks ...Hook) {
	c.hooks.RefreshSession = append(c.hooks.RefreshSession, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `refreshsession.Intercept(f(g(h())))`.
func (c *RefreshSessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.RefreshSession = append(c.inters.RefreshSession, interceptors...)
}

// Create returns a builder for creating a RefreshSession entity.
func (c *RefreshSessionClient) Create() *RefreshSessionCreate {
	mutation := newRefreshSessionMutation(c.config, OpCreate)
	return &RefreshSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RefreshSession entities.
func (c *RefreshSessionClient) CreateBulk(builders ...*RefreshSessionCreate) *RefreshSessionCreateBulk {
	return &RefreshSessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RefreshSessionClient) MapCreateBulk(slice any, setFunc func(*RefreshSessionCreate, int)) *RefreshSessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RefreshSessionCreateBulk{err: fmt.Errorf("calling to RefreshSessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RefreshSessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RefreshSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RefreshSession.
func (c *RefreshSessionClient) Update() *RefreshSessionUpdate {
	mutation := newRefreshSessionMutation(c.config, OpUpdate)
	return &RefreshSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RefreshSessionClient) UpdateOne(_m *RefreshSession) *RefreshSessionUpdateOne {
	mutation := newRefreshSessionMutation(c.config, OpUpdateOne, withRefreshSession(_m))
	return &RefreshSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RefreshSessionClient) UpdateOneID(id int) *RefreshSessionUpdateOne {
	mutation := newRefreshSessionMutation(c.config, OpUpdateOne, withRefreshSessionID(id))
	return &RefreshSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RefreshSession.
func (c *RefreshSessionClient) Delete() *RefreshSessionDelete {
	mutation := newRefreshSessionMutation(c.config, OpDelete)
	return &RefreshSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RefreshSessionClient) DeleteOne(_m *RefreshSession) *RefreshSessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RefreshSessionClient) DeleteOneID(id int) *RefreshSessionDeleteOne {
	builder := c.Delete().Where(refreshsession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RefreshSessionDeleteOne{builder}
}

// Query returns a query builder for RefreshSession.
func (c *RefreshSessionClient) Query() *RefreshSessionQuery {
	return &RefreshSessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRefreshSession},
		inters: c.Interceptors(),
	}
}

// Get returns a RefreshSession entity by its id.
func (c *RefreshSessionClient) Get(ctx context.Context, id int) (*RefreshSession, error) {
	return c.Query().Where(refreshsession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RefreshSessionClient) GetX(ctx context.Context, id int) *RefreshSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a RefreshSession.
func (c *RefreshSessionClient) QueryUser(_m *RefreshSession) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(refreshsession.Table, refreshsession.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, refreshsession.UserTable, refreshsession.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *RefreshSessionClient) Hooks() []Hook {
	return c.hooks.RefreshSession
}

// Interceptors returns the client interceptors.
func (c *RefreshSessionClient) Interceptors() []Interceptor {
	return c.inters.RefreshSession
}

func (c *RefreshSessionClient) mutate(ctx context.Context, m *RefreshSessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RefreshSessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RefreshSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RefreshSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RefreshSessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RefreshSession mutation op: %q", m.Op())
	}
}

// TeacherInvitationClient is a client for the TeacherInvitation schema.
type TeacherInvitationClient struct {
	config
}

// NewTeacherInvitationClient returns a client for the TeacherInvitation from the given config.
func NewTeacherInvitationClient(c config) *TeacherInvitationClient {
	return &TeacherInvitationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `teacherinvitation.Hooks(f(g(h())))`.
func (c *TeacherInvitationClient) Use(hooks ...Hook) {
	c.hooks.TeacherInvitation = append(c.hooks.TeacherInvitation, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `teacherinvitation.Intercept(f(g(h())))`.
func (c *TeacherInvitationClient) Intercept(interceptors ...Interceptor) {
	c.inters.TeacherInvitation = append(c.inters.TeacherInvitation, interceptors...)
}

// Create returns a builder for creating a TeacherInvitation entity.
func (c *TeacherInvitationClient) Create() *TeacherInvitationCreate {
	mutation := newTeacherInvitationMutation(c.config, OpCreate)
	return &TeacherInvitationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TeacherInvitation entities.
func (c *TeacherInvitationClient) CreateBulk(builders ...*TeacherInvitationCreate) *TeacherInvitationCreateBulk {
	return &TeacherInvitationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TeacherInvitationClient) MapCreateBulk(slice any, setFunc func(*TeacherInvitationCreate, int)) *TeacherInvitationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TeacherInvitationCreateBulk{err: fmt.Errorf("calling to TeacherInvitationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TeacherInvitationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TeacherInvitationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TeacherInvitation.
func (c *TeacherInvitationClient) Update() *TeacherInvitationUpdate {
	mutation := newTeacherInvitationMutation(c.config, OpUpdate)
	return &TeacherInvitationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TeacherInvitationClient) UpdateOne(_m *TeacherInvitation) *TeacherInvitationUpdateOne {
	mutation := newTeacherInvitationMutation(c.config, OpUpdateOne, withTeacherInvitation(_m))
	return &TeacherInvitationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TeacherInvitationClient) UpdateOneID(id int) *TeacherInvitationUpdateOne {
	mutation := newTeacherInvitationMutation(c.config, OpUpdateOne, withTeacherInvitationID(id))
	return &TeacherInvitationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TeacherInvitation.
func (c *TeacherInvitationClient) Delete() *TeacherInvitationDelete {
	mutation := newTeacherInvitationMutation(c.config, OpDelete)
	return &TeacherInvitationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TeacherInvitationClient) DeleteOne(_m *TeacherInvitation) *TeacherInvitationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TeacherInvitationClient) DeleteOneID(id int) *TeacherInvitationDeleteOne {
	builder := c.Delete().Where(teacherinvitation.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TeacherInvitationDeleteOne{builder}
}

// Query returns a query builder for TeacherInvitation.
func (c *TeacherInvitationClient) Query() *TeacherInvitationQuery {
	return &TeacherInvitationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTeacherInvitation},
		inters: c.Interceptors(),
	}
}

// Get returns a TeacherInvitation entity by its id.
func (c *TeacherInvitationClient) Get(ctx context.Context, id int) (*TeacherInvitation, error) {
	return c.Query().Where(teacherinvitation.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TeacherInvitationClient) GetX(ctx context.Context, id int) *TeacherInvitation {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryCourse queries the course edge of a TeacherInvitation.
func (c *TeacherInvitationClient) QueryCourse(_m *TeacherInvitation) *CourseQuery {
	query := (&CourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(teacherinvitation.Table, teacherinvitation.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, teacherinvitation.CourseTable, teacherinvitation.CourseColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TeacherInvitationClient) Hooks() []Hook {
	return c.hooks.TeacherInvitation
}

// Interceptors returns the client interceptors.
func (c *TeacherInvitationClient) Interceptors() []Interceptor {
	return c.inters.TeacherInvitation
}

func (c *TeacherInvitationClient) mutate(ctx context.Context, m *TeacherInvitationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TeacherInvitationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TeacherInvitationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TeacherInvitationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TeacherInvitationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TeacherInvitation mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryMemberships queries the memberships edge of a User.
func (c *UserClient) QueryMemberships(_m *User) *CourseMembershipQuery {
	query := (&CourseMembershipClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(coursemembership.Table, coursemembership.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.MembershipsTable, user.MembershipsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOwnedCourses queries the owned_courses edge of a User.
func (c *UserClient) QueryOwnedCourses(_m *User) *CourseQuery {
	query := (&CourseClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(course.Table, course.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.OwnedCoursesTable, user.OwnedCoursesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryRefreshSessions queries the refresh_sessions edge of a User.
func (c *UserClient) QueryRefreshSessions(_m *User) *RefreshSessionQuery {
	query := (&RefreshSessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(refreshsession.Table, refreshsession.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.RefreshSessionsTable, user.RefreshSessionsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Course, CourseMembership, RefreshSession, TeacherInvitation, User []ent.Hook
	}
	inters struct {
		Course, CourseMembership, RefreshSession, TeacherInvitation,
		User []ent.Interceptor
	}
)
