// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/legitahmad/logithm-backend/ent/course"
	"github.com/legitahmad/logithm-backend/ent/coursemembership"
	"github.com/legitahmad/logithm-backend/ent/user"
)

// CourseMembershipCreate is the builder for creating a CourseMembership entity.
type CourseMembershipCreate struct {
	config
	mutation *CourseMembershipMutation
	hooks    []Hook
}

// SetRole sets the "role" field.
func (_c *CourseMembershipCreate) SetRole(v coursemembership.Role) *CourseMembershipCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CourseMembershipCreate) SetUserID(v int) *CourseMembershipCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCourseID sets the "course_id" field.
func (_c *CourseMembershipCreate) SetCourseID(v int) *CourseMembershipCreate {
	_c.mutation.SetCourseID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CourseMembershipCreate) SetCreatedAt(v time.Time) *CourseMembershipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CourseMembershipCreate) SetUser(v *User) *CourseMembershipCreate {
	return _c.SetUserID(v.ID)
}

// SetCourse sets the "course" edge to the Course entity.
func (_c *CourseMembershipCreate) SetCourse(v *Course) *CourseMembershipCreate {
	return _c.SetCourseID(v.ID)
}

// Mutation returns the CourseMembershipMutation object of the builder.
func (_c *CourseMembershipCreate) Mutation() *CourseMembershipMutation {
	return _c.mutation
}

// Save creates the CourseMembership in the database.
func (_c *CourseMembershipCreate) Save(ctx context.Context) (*CourseMembership, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseMembershipCreate) SaveX(ctx context.Context) *CourseMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseMembershipCreate) check() error {
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "CourseMembership.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := coursemembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "CourseMembership.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CourseMembership.user_id"`)}
	}
	if _, ok := _c.mutation.CourseID(); !ok {
		return &ValidationError{Name: "course_id", err: errors.New(`ent: missing required field "CourseMembership.course_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CourseMembership.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CourseMembership.user"`)}
	}
	if len(_c.mutation.CourseIDs()) == 0 {
		return &ValidationError{Name: "course", err: errors.New(`ent: missing required edge "CourseMembership.course"`)}
	}
	return nil
}

func (_c *CourseMembershipCreate) sqlSave(ctx context.Context) (*CourseMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseMembershipCreate) createSpec() (*CourseMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &CourseMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coursemembership.Table, sqlgraph.NewFieldSpec(coursemembership.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(coursemembership.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(coursemembership.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.UserTable,
			Columns: []string{coursemembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.CourseTable,
			Columns: []string{coursemembership.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CourseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CourseMembershipCreateBulk is the builder for creating many CourseMembership entities in bulk.
type CourseMembershipCreateBulk struct {
	config
	err      error
	builders []*CourseMembershipCreate
}

// Save creates the CourseMembership entities in the database.
func (_c *CourseMembershipCreateBulk) Save(ctx context.Context) ([]*CourseMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CourseMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseMembershipCreateBulk) SaveX(ctx context.Context) []*CourseMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
