// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/legitahmad/logithm-backend/ent/course"
	"github.com/legitahmad/logithm-backend/ent/coursemembership"
	"github.com/legitahmad/logithm-backend/ent/predicate"
	"github.com/legitahmad/logithm-backend/ent/user"
)

// CourseMembershipUpdate is the builder for updating CourseMembership entities.
type CourseMembershipUpdate struct {
	config
	hooks    []Hook
	mutation *CourseMembershipMutation
}

// Where appends a list predicates to the CourseMembershipUpdate builder.
func (_u *CourseMembershipUpdate) Where(ps ...predicate.CourseMembership) *CourseMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRole sets the "role" field.
func (_u *CourseMembershipUpdate) SetRole(v coursemembership.Role) *CourseMembershipUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *CourseMembershipUpdate) SetNillableRole(v *coursemembership.Role) *CourseMembershipUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CourseMembershipUpdate) SetUserID(v int) *CourseMembershipUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CourseMembershipUpdate) SetNillableUserID(v *int) *CourseMembershipUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *CourseMembershipUpdate) SetCourseID(v int) *CourseMembershipUpdate {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *CourseMembershipUpdate) SetNillableCourseID(v *int) *CourseMembershipUpdate {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CourseMembershipUpdate) SetUser(v *User) *CourseMembershipUpdate {
	return _u.SetUserID(v.ID)
}

// SetCourse sets the "course" edge to the Course entity.
func (_u *CourseMembershipUpdate) SetCourse(v *Course) *CourseMembershipUpdate {
	return _u.SetCourseID(v.ID)
}

// Mutation returns the CourseMembershipMutation object of the builder.
func (_u *CourseMembershipUpdate) Mutation() *CourseMembershipMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CourseMembershipUpdate) ClearUser() *CourseMembershipUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearCourse clears the "course" edge to the Course entity.
func (_u *CourseMembershipUpdate) ClearCourse() *CourseMembershipUpdate {
	_u.mutation.ClearCourse()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CourseMembershipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CourseMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CourseMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CourseMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CourseMembershipUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := coursemembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "CourseMembership.role": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CourseMembership.user"`)
	}
	if _u.mutation.CourseCleared() && len(_u.mutation.CourseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CourseMembership.course"`)
	}
	return nil
}

func (_u *CourseMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(coursemembership.Table, coursemembership.Columns, sqlgraph.NewFieldSpec(coursemembership.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(coursemembership.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.UserTable,
			Columns: []string{coursemembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.UserTable,
			Columns: []string{coursemembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.CourseTable,
			Columns: []string{coursemembership.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.CourseTable,
			Columns: []string{coursemembership.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coursemembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CourseMembershipUpdateOne is the builder for updating a single CourseMembership entity.
type CourseMembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CourseMembershipMutation
}

// SetRole sets the "role" field.
func (_u *CourseMembershipUpdateOne) SetRole(v coursemembership.Role) *CourseMembershipUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *CourseMembershipUpdateOne) SetNillableRole(v *coursemembership.Role) *CourseMembershipUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CourseMembershipUpdateOne) SetUserID(v int) *CourseMembershipUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CourseMembershipUpdateOne) SetNillableUserID(v *int) *CourseMembershipUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *CourseMembershipUpdateOne) SetCourseID(v int) *CourseMembershipUpdateOne {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *CourseMembershipUpdateOne) SetNillableCourseID(v *int) *CourseMembershipUpdateOne {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CourseMembershipUpdateOne) SetUser(v *User) *CourseMembershipUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetCourse sets the "course" edge to the Course entity.
func (_u *CourseMembershipUpdateOne) SetCourse(v *Course) *CourseMembershipUpdateOne {
	return _u.SetCourseID(v.ID)
}

// Mutation returns the CourseMembershipMutation object of the builder.
func (_u *CourseMembershipUpdateOne) Mutation() *CourseMembershipMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CourseMembershipUpdateOne) ClearUser() *CourseMembershipUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearCourse clears the "course" edge to the Course entity.
func (_u *CourseMembershipUpdateOne) ClearCourse() *CourseMembershipUpdateOne {
	_u.mutation.ClearCourse()
	return _u
}

// Where appends a list predicates to the CourseMembershipUpdate builder.
func (_u *CourseMembershipUpdateOne) Where(ps ...predicate.CourseMembership) *CourseMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CourseMembershipUpdateOne) Select(field string, fields ...string) *CourseMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CourseMembership entity.
func (_u *CourseMembershipUpdateOne) Save(ctx context.Context) (*CourseMembership, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CourseMembershipUpdateOne) SaveX(ctx context.Context) *CourseMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CourseMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CourseMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CourseMembershipUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := coursemembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "CourseMembership.role": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CourseMembership.user"`)
	}
	if _u.mutation.CourseCleared() && len(_u.mutation.CourseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CourseMembership.course"`)
	}
	return nil
}

func (_u *CourseMembershipUpdateOne) sqlSave(ctx context.Context) (_node *CourseMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(coursemembership.Table, coursemembership.Columns, sqlgraph.NewFieldSpec(coursemembership.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CourseMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coursemembership.FieldID)
		for _, f := range fields {
			if !coursemembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != coursemembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(coursemembership.FieldRole, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.UserTable,
			Columns: []string{coursemembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.UserTable,
			Columns: []string{coursemembership.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.CourseTable,
			Columns: []string{coursemembership.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   coursemembership.CourseTable,
			Columns: []string{coursemembership.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CourseMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{coursemembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
