// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/legitahmad/logithm-backend/ent/course"
	"github.com/legitahmad/logithm-backend/ent/coursemembership"
	"github.com/legitahmad/logithm-backend/ent/teacherinvitation"
	"github.com/legitahmad/logithm-backend/ent/user"
)

// CourseCreate is the builder for creating a Course entity.
type CourseCreate struct {
	config
	mutation *CourseMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CourseCreate) SetName(v string) *CourseCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CourseCreate) SetDescription(v string) *CourseCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CourseCreate) SetNillableDescription(v *string) *CourseCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetJoinCode sets the "join_code" field.
func (_c *CourseCreate) SetJoinCode(v string) *CourseCreate {
	_c.mutation.SetJoinCode(v)
	return _c
}

// SetOwnerID sets the "owner_id" field.
func (_c *CourseCreate) SetOwnerID(v int) *CourseCreate {
	_c.mutation.SetOwnerID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CourseCreate) SetCreatedAt(v time.Time) *CourseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CourseCreate) SetUpdatedAt(v time.Time) *CourseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *CourseCreate) SetOwner(v *User) *CourseCreate {
	return _c.SetOwnerID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the CourseMembership entity by IDs.
func (_c *CourseCreate) AddMembershipIDs(ids ...int) *CourseCreate {
	_c.mutation.AddMembershipIDs(ids...)
	return _c
}

// AddMemberships adds the "memberships" edges to the CourseMembership entity.
func (_c *CourseCreate) AddMemberships(v ...*CourseMembership) *CourseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMembershipIDs(ids...)
}

// AddTeacherInvitationIDs adds the "teacher_invitations" edge to the TeacherInvitation entity by IDs.
func (_c *CourseCreate) AddTeacherInvitationIDs(ids ...int) *CourseCreate {
	_c.mutation.AddTeacherInvitationIDs(ids...)
	return _c
}

// AddTeacherInvitations adds the "teacher_invitations" edges to the TeacherInvitation entity.
func (_c *CourseCreate) AddTeacherInvitations(v ...*TeacherInvitation) *CourseCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeacherInvitationIDs(ids...)
}

// Mutation returns the CourseMutation object of the builder.
func (_c *CourseCreate) Mutation() *CourseMutation {
	return _c.mutation
}

// Save creates the Course in the database.
func (_c *CourseCreate) Save(ctx context.Context) (*Course, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CourseCreate) SaveX(ctx context.Context) *Course {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CourseCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := course.DefaultDescription
		_c.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CourseCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Course.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := course.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Course.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Course.description"`)}
	}
	if _, ok := _c.mutation.JoinCode(); !ok {
		return &ValidationError{Name: "join_code", err: errors.New(`ent: missing required field "Course.join_code"`)}
	}
	if v, ok := _c.mutation.JoinCode(); ok {
		if err := course.JoinCodeValidator(v); err != nil {
			return &ValidationError{Name: "join_code", err: fmt.Errorf(`ent: validator failed for field "Course.join_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Course.owner_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Course.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Course.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Course.owner"`)}
	}
	return nil
}

func (_c *CourseCreate) sqlSave(ctx context.Context) (*Course, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CourseCreate) createSpec() (*Course, *sqlgraph.CreateSpec) {
	var (
		_node = &Course{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(course.Table, sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(course.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(course.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.JoinCode(); ok {
		_spec.SetField(course.FieldJoinCode, field.TypeString, value)
		_node.JoinCode = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(course.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(course.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   course.OwnerTable,
			Columns: []string{course.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.MembershipsTable,
			Columns: []string{course.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(coursemembership.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeacherInvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   course.TeacherInvitationsTable,
			Columns: []string{course.TeacherInvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacherinvitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CourseCreateBulk is the builder for creating many Course entities in bulk.
type CourseCreateBulk struct {
	config
	err      error
	builders []*CourseCreate
}

// Save creates the Course entities in the database.
func (_c *CourseCreateBulk) Save(ctx context.Context) ([]*Course, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Course, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CourseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CourseCreateBulk) SaveX(ctx context.Context) []*Course {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CourseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CourseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
