// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/legitahmad/logithm-backend/ent/course"
	"github.com/legitahmad/logithm-backend/ent/teacherinvitation"
)

// TeacherInvitation is the model entity for the TeacherInvitation schema.
type TeacherInvitation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"-"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CourseID holds the value of the "course_id" field.
	CourseID int `json:"course_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// AcceptedAt holds the value of the "accepted_at" field.
	AcceptedAt *time.Time `json:"accepted_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeacherInvitationQuery when eager-loading is set.
	Edges        TeacherInvitationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeacherInvitationEdges holds the relations/edges for other nodes in the graph.
type TeacherInvitationEdges struct {
	// Course holds the value of the course edge.
	Course *Course `json:"course,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CourseOrErr returns the Course value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeacherInvitationEdges) CourseOrErr() (*Course, error) {
	if e.Course != nil {
		return e.Course, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: course.Label}
	}
	return nil, &NotLoadedError{edge: "course"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeacherInvitation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teacherinvitation.FieldID, teacherinvitation.FieldCourseID:
			values[i] = new(sql.NullInt64)
		case teacherinvitation.FieldEmail, teacherinvitation.FieldTokenHash, teacherinvitation.FieldStatus:
			values[i] = new(sql.NullString)
		case teacherinvitation.FieldExpiresAt, teacherinvitation.FieldAcceptedAt, teacherinvitation.FieldRevokedAt, teacherinvitation.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeacherInvitation fields.
func (_m *TeacherInvitation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teacherinvitation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case teacherinvitation.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case teacherinvitation.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case teacherinvitation.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case teacherinvitation.FieldCourseID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field course_id", values[i])
			} else if value.Valid {
				_m.CourseID = int(value.Int64)
			}
		case teacherinvitation.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case teacherinvitation.FieldAcceptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_at", values[i])
			} else if value.Valid {
				_m.AcceptedAt = new(time.Time)
				*_m.AcceptedAt = value.Time
			}
		case teacherinvitation.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case teacherinvitation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeacherInvitation.
// This includes values selected through modifiers, order, etc.
func (_m *TeacherInvitation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCourse queries the "course" edge of the TeacherInvitation entity.
func (_m *TeacherInvitation) QueryCourse() *CourseQuery {
	return NewTeacherInvitationClient(_m.config).QueryCourse(_m)
}

// Update returns a builder for updating this TeacherInvitation.
// Note that you need to call TeacherInvitation.Unwrap() before calling this method if this TeacherInvitation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeacherInvitation) Update() *TeacherInvitationUpdateOne {
	return NewTeacherInvitationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeacherInvitation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeacherInvitation) Unwrap() *TeacherInvitation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeacherInvitation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeacherInvitation) String() string {
	var builder strings.Builder
	builder.WriteString("TeacherInvitation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("token_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("course_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CourseID))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.AcceptedAt; v != nil {
		builder.WriteString("accepted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TeacherInvitations is a parsable slice of TeacherInvitation.
type TeacherInvitations []*TeacherInvitation
