// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/legitahmad/logithm-backend/ent/course"
	"github.com/legitahmad/logithm-backend/ent/teacherinvitation"
)

// TeacherInvitationCreate is the builder for creating a TeacherInvitation entity.
type TeacherInvitationCreate struct {
	config
	mutation *TeacherInvitationMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *TeacherInvitationCreate) SetEmail(v string) *TeacherInvitationCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *TeacherInvitationCreate) SetTokenHash(v string) *TeacherInvitationCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TeacherInvitationCreate) SetStatus(v string) *TeacherInvitationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TeacherInvitationCreate) SetNillableStatus(v *string) *TeacherInvitationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCourseID sets the "course_id" field.
func (_c *TeacherInvitationCreate) SetCourseID(v int) *TeacherInvitationCreate {
	_c.mutation.SetCourseID(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TeacherInvitationCreate) SetExpiresAt(v time.Time) *TeacherInvitationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetAcceptedAt sets the "accepted_at" field.
func (_c *TeacherInvitationCreate) SetAcceptedAt(v time.Time) *TeacherInvitationCreate {
	_c.mutation.SetAcceptedAt(v)
	return _c
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_c *TeacherInvitationCreate) SetNillableAcceptedAt(v *time.Time) *TeacherInvitationCreate {
	if v != nil {
		_c.SetAcceptedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *TeacherInvitationCreate) SetRevokedAt(v time.Time) *TeacherInvitationCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *TeacherInvitationCreate) SetNillableRevokedAt(v *time.Time) *TeacherInvitationCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeacherInvitationCreate) SetCreatedAt(v time.Time) *TeacherInvitationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetCourse sets the "course" edge to the Course entity.
func (_c *TeacherInvitationCreate) SetCourse(v *Course) *TeacherInvitationCreate {
	return _c.SetCourseID(v.ID)
}

// Mutation returns the TeacherInvitationMutation object of the builder.
func (_c *TeacherInvitationCreate) Mutation() *TeacherInvitationMutation {
	return _c.mutation
}

// Save creates the TeacherInvitation in the database.
func (_c *TeacherInvitationCreate) Save(ctx context.Context) (*TeacherInvitation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeacherInvitationCreate) SaveX(ctx context.Context) *TeacherInvitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeacherInvitationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeacherInvitationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeacherInvitationCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := teacherinvitation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeacherInvitationCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "TeacherInvitation.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := teacherinvitation.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TeacherInvitation.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "TeacherInvitation.token_hash"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TeacherInvitation.status"`)}
	}
	if _, ok := _c.mutation.CourseID(); !ok {
		return &ValidationError{Name: "course_id", err: errors.New(`ent: missing required field "TeacherInvitation.course_id"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "TeacherInvitation.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeacherInvitation.created_at"`)}
	}
	if len(_c.mutation.CourseIDs()) == 0 {
		return &ValidationError{Name: "course", err: errors.New(`ent: missing required edge "TeacherInvitation.course"`)}
	}
	return nil
}

func (_c *TeacherInvitationCreate) sqlSave(ctx context.Context) (*TeacherInvitation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeacherInvitationCreate) createSpec() (*TeacherInvitation, *sqlgraph.CreateSpec) {
	var (
		_node = &TeacherInvitation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teacherinvitation.Table, sqlgraph.NewFieldSpec(teacherinvitation.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(teacherinvitation.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(teacherinvitation.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(teacherinvitation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(teacherinvitation.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.AcceptedAt(); ok {
		_spec.SetField(teacherinvitation.FieldAcceptedAt, field.TypeTime, value)
		_node.AcceptedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(teacherinvitation.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teacherinvitation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teacherinvitation.CourseTable,
			Columns: []string{teacherinvitation.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CourseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TeacherInvitationCreateBulk is the builder for creating many TeacherInvitation entities in bulk.
type TeacherInvitationCreateBulk struct {
	config
	err      error
	builders []*TeacherInvitationCreate
}

// Save creates the TeacherInvitation entities in the database.
func (_c *TeacherInvitationCreateBulk) Save(ctx context.Context) ([]*TeacherInvitation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeacherInvitation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeacherInvitationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeacherInvitationCreateBulk) SaveX(ctx context.Context) []*TeacherInvitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeacherInvitationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeacherInvitationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
