// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/legitahmad/logithm-backend/ent/predicate"
	"github.com/legitahmad/logithm-backend/ent/teacherinvitation"
)

// TeacherInvitationDelete is the builder for deleting a TeacherInvitation entity.
type TeacherInvitationDelete struct {
	config
	hooks    []Hook
	mutation *TeacherInvitationMutation
}

// Where appends a list predicates to the TeacherInvitationDelete builder.
func (_d *TeacherInvitationDelete) Where(ps ...predicate.TeacherInvitation) *TeacherInvitationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TeacherInvitationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeacherInvitationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TeacherInvitationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(teacherinvitation.Table, sqlgraph.NewFieldSpec(teacherinvitation.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TeacherInvitationDeleteOne is the builder for deleting a single TeacherInvitation entity.
type TeacherInvitationDeleteOne struct {
	_d *TeacherInvitationDelete
}

// Where appends a list predicates to the TeacherInvitationDelete builder.
func (_d *TeacherInvitationDeleteOne) Where(ps ...predicate.TeacherInvitation) *TeacherInvitationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TeacherInvitationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teacherinvitation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TeacherInvitationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
