// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/legitahmad/logithm-backend/ent/course"
	"github.com/legitahmad/logithm-backend/ent/predicate"
	"github.com/legitahmad/logithm-backend/ent/teacherinvitation"
)

// TeacherInvitationUpdate is the builder for updating TeacherInvitation entities.
type TeacherInvitationUpdate struct {
	config
	hooks    []Hook
	mutation *TeacherInvitationMutation
}

// Where appends a list predicates to the TeacherInvitationUpdate builder.
func (_u *TeacherInvitationUpdate) Where(ps ...predicate.TeacherInvitation) *TeacherInvitationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *TeacherInvitationUpdate) SetEmail(v string) *TeacherInvitationUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TeacherInvitationUpdate) SetNillableEmail(v *string) *TeacherInvitationUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *TeacherInvitationUpdate) SetTokenHash(v string) *TeacherInvitationUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *TeacherInvitationUpdate) SetNillableTokenHash(v *string) *TeacherInvitationUpdate {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeacherInvitationUpdate) SetStatus(v string) *TeacherInvitationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeacherInvitationUpdate) SetNillableStatus(v *string) *TeacherInvitationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *TeacherInvitationUpdate) SetCourseID(v int) *TeacherInvitationUpdate {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *TeacherInvitationUpdate) SetNillableCourseID(v *int) *TeacherInvitationUpdate {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TeacherInvitationUpdate) SetExpiresAt(v time.Time) *TeacherInvitationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TeacherInvitationUpdate) SetNillableExpiresAt(v *time.Time) *TeacherInvitationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *TeacherInvitationUpdate) SetAcceptedAt(v time.Time) *TeacherInvitationUpdate {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *TeacherInvitationUpdate) SetNillableAcceptedAt(v *time.Time) *TeacherInvitationUpdate {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *TeacherInvitationUpdate) ClearAcceptedAt() *TeacherInvitationUpdate {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *TeacherInvitationUpdate) SetRevokedAt(v time.Time) *TeacherInvitationUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *TeacherInvitationUpdate) SetNillableRevokedAt(v *time.Time) *TeacherInvitationUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *TeacherInvitationUpdate) ClearRevokedAt() *TeacherInvitationUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetCourse sets the "course" edge to the Course entity.
func (_u *TeacherInvitationUpdate) SetCourse(v *Course) *TeacherInvitationUpdate {
	return _u.SetCourseID(v.ID)
}

// Mutation returns the TeacherInvitationMutation object of the builder.
func (_u *TeacherInvitationUpdate) Mutation() *TeacherInvitationMutation {
	return _u.mutation
}

// ClearCourse clears the "course" edge to the Course entity.
func (_u *TeacherInvitationUpdate) ClearCourse() *TeacherInvitationUpdate {
	_u.mutation.ClearCourse()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeacherInvitationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeacherInvitationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeacherInvitationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeacherInvitationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeacherInvitationUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := teacherinvitation.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TeacherInvitation.email": %w`, err)}
		}
	}
	if _u.mutation.CourseCleared() && len(_u.mutation.CourseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeacherInvitation.course"`)
	}
	return nil
}

func (_u *TeacherInvitationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teacherinvitation.Table, teacherinvitation.Columns, sqlgraph.NewFieldSpec(teacherinvitation.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(teacherinvitation.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(teacherinvitation.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teacherinvitation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(teacherinvitation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(teacherinvitation.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(teacherinvitation.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(teacherinvitation.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(teacherinvitation.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teacherinvitation.CourseTable,
			Columns: []string{teacherinvitation.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teacherinvitation.CourseTable,
			Columns: []string{teacherinvitation.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teacherinvitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeacherInvitationUpdateOne is the builder for updating a single TeacherInvitation entity.
type TeacherInvitationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeacherInvitationMutation
}

// SetEmail sets the "email" field.
func (_u *TeacherInvitationUpdateOne) SetEmail(v string) *TeacherInvitationUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *TeacherInvitationUpdateOne) SetNillableEmail(v *string) *TeacherInvitationUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *TeacherInvitationUpdateOne) SetTokenHash(v string) *TeacherInvitationUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (_u *TeacherInvitationUpdateOne) SetNillableTokenHash(v *string) *TeacherInvitationUpdateOne {
	if v != nil {
		_u.SetTokenHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeacherInvitationUpdateOne) SetStatus(v string) *TeacherInvitationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeacherInvitationUpdateOne) SetNillableStatus(v *string) *TeacherInvitationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCourseID sets the "course_id" field.
func (_u *TeacherInvitationUpdateOne) SetCourseID(v int) *TeacherInvitationUpdateOne {
	_u.mutation.SetCourseID(v)
	return _u
}

// SetNillableCourseID sets the "course_id" field if the given value is not nil.
func (_u *TeacherInvitationUpdateOne) SetNillableCourseID(v *int) *TeacherInvitationUpdateOne {
	if v != nil {
		_u.SetCourseID(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *TeacherInvitationUpdateOne) SetExpiresAt(v time.Time) *TeacherInvitationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *TeacherInvitationUpdateOne) SetNillableExpiresAt(v *time.Time) *TeacherInvitationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetAcceptedAt sets the "accepted_at" field.
func (_u *TeacherInvitationUpdateOne) SetAcceptedAt(v time.Time) *TeacherInvitationUpdateOne {
	_u.mutation.SetAcceptedAt(v)
	return _u
}

// SetNillableAcceptedAt sets the "accepted_at" field if the given value is not nil.
func (_u *TeacherInvitationUpdateOne) SetNillableAcceptedAt(v *time.Time) *TeacherInvitationUpdateOne {
	if v != nil {
		_u.SetAcceptedAt(*v)
	}
	return _u
}

// ClearAcceptedAt clears the value of the "accepted_at" field.
func (_u *TeacherInvitationUpdateOne) ClearAcceptedAt() *TeacherInvitationUpdateOne {
	_u.mutation.ClearAcceptedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *TeacherInvitationUpdateOne) SetRevokedAt(v time.Time) *TeacherInvitationUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *TeacherInvitationUpdateOne) SetNillableRevokedAt(v *time.Time) *TeacherInvitationUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *TeacherInvitationUpdateOne) ClearRevokedAt() *TeacherInvitationUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetCourse sets the "course" edge to the Course entity.
func (_u *TeacherInvitationUpdateOne) SetCourse(v *Course) *TeacherInvitationUpdateOne {
	return _u.SetCourseID(v.ID)
}

// Mutation returns the TeacherInvitationMutation object of the builder.
func (_u *TeacherInvitationUpdateOne) Mutation() *TeacherInvitationMutation {
	return _u.mutation
}

// ClearCourse clears the "course" edge to the Course entity.
func (_u *TeacherInvitationUpdateOne) ClearCourse() *TeacherInvitationUpdateOne {
	_u.mutation.ClearCourse()
	return _u
}

// Where appends a list predicates to the TeacherInvitationUpdate builder.
func (_u *TeacherInvitationUpdateOne) Where(ps ...predicate.TeacherInvitation) *TeacherInvitationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeacherInvitationUpdateOne) Select(field string, fields ...string) *TeacherInvitationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeacherInvitation entity.
func (_u *TeacherInvitationUpdateOne) Save(ctx context.Context) (*TeacherInvitation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeacherInvitationUpdateOne) SaveX(ctx context.Context) *TeacherInvitation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeacherInvitationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeacherInvitationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeacherInvitationUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := teacherinvitation.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "TeacherInvitation.email": %w`, err)}
		}
	}
	if _u.mutation.CourseCleared() && len(_u.mutation.CourseIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeacherInvitation.course"`)
	}
	return nil
}

func (_u *TeacherInvitationUpdateOne) sqlSave(ctx context.Context) (_node *TeacherInvitation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teacherinvitation.Table, teacherinvitation.Columns, sqlgraph.NewFieldSpec(teacherinvitation.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeacherInvitation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teacherinvitation.FieldID)
		for _, f := range fields {
			if !teacherinvitation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teacherinvitation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(teacherinvitation.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(teacherinvitation.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(teacherinvitation.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(teacherinvitation.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AcceptedAt(); ok {
		_spec.SetField(teacherinvitation.FieldAcceptedAt, field.TypeTime, value)
	}
	if _u.mutation.AcceptedAtCleared() {
		_spec.ClearField(teacherinvitation.FieldAcceptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(teacherinvitation.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(teacherinvitation.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.CourseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teacherinvitation.CourseTable,
			Columns: []string{teacherinvitation.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CourseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teacherinvitation.CourseTable,
			Columns: []string{teacherinvitation.CourseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(course.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeacherInvitation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teacherinvitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
