// Code generated by ent, DO NOT EDIT.

package refreshsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/legitahmad/logithm-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldSessionID, v))
}

// FamilyID applies equality check predicate on the "family_id" field. It's identical to FamilyIDEQ.
func FamilyID(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldFamilyID, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldTokenHash, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldUserID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldCreatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContainsFold(FieldSessionID, v))
}

// FamilyIDEQ applies the EQ predicate on the "family_id" field.
func FamilyIDEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldFamilyID, v))
}

// FamilyIDNEQ applies the NEQ predicate on the "family_id" field.
func FamilyIDNEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldFamilyID, v))
}

// FamilyIDIn applies the In predicate on the "family_id" field.
func FamilyIDIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldFamilyID, vs...))
}

// FamilyIDNotIn applies the NotIn predicate on the "family_id" field.
func FamilyIDNotIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldFamilyID, vs...))
}

// FamilyIDGT applies the GT predicate on the "family_id" field.
func FamilyIDGT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldFamilyID, v))
}

// FamilyIDGTE applies the GTE predicate on the "family_id" field.
func FamilyIDGTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldFamilyID, v))
}

// FamilyIDLT applies the LT predicate on the "family_id" field.
func FamilyIDLT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldFamilyID, v))
}

// FamilyIDLTE applies the LTE predicate on the "family_id" field.
func FamilyIDLTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldFamilyID, v))
}

// FamilyIDContains applies the Contains predicate on the "family_id" field.
func FamilyIDContains(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContains(FieldFamilyID, v))
}

// FamilyIDHasPrefix applies the HasPrefix predicate on the "family_id" field.
func FamilyIDHasPrefix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasPrefix(FieldFamilyID, v))
}

// FamilyIDHasSuffix applies the HasSuffix predicate on the "family_id" field.
func FamilyIDHasSuffix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasSuffix(FieldFamilyID, v))
}

// FamilyIDEqualFold applies the EqualFold predicate on the "family_id" field.
func FamilyIDEqualFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEqualFold(FieldFamilyID, v))
}

// FamilyIDContainsFold applies the ContainsFold predicate on the "family_id" field.
func FamilyIDContainsFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContainsFold(FieldFamilyID, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashContains applies the Contains predicate on the "token_hash" field.
func TokenHashContains(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContains(FieldTokenHash, v))
}

// TokenHashHasPrefix applies the HasPrefix predicate on the "token_hash" field.
func TokenHashHasPrefix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasPrefix(FieldTokenHash, v))
}

// TokenHashHasSuffix applies the HasSuffix predicate on the "token_hash" field.
func TokenHashHasSuffix(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldHasSuffix(FieldTokenHash, v))
}

// TokenHashEqualFold applies the EqualFold predicate on the "token_hash" field.
func TokenHashEqualFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEqualFold(FieldTokenHash, v))
}

// TokenHashContainsFold applies the ContainsFold predicate on the "token_hash" field.
func TokenHashContainsFold(v string) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldContainsFold(FieldTokenHash, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldUserID, vs...))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotNull(FieldRevokedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RefreshSession {
	return predicate.RefreshSession(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RefreshSession {
	return predicate.RefreshSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RefreshSession {
	return predicate.RefreshSession(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RefreshSession) predicate.RefreshSession {
	return predicate.RefreshSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RefreshSession) predicate.RefreshSession {
	return predicate.RefreshSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RefreshSession) predicate.RefreshSession {
	return predicate.RefreshSession(sql.NotPredicates(p))
}
