// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Assignment is the predicate function for assignment builders.
type Assignment func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// Result is the predicate function for result builders.
type Result func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// Submission is the predicate function for submission builders.
type Submission func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)
