// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// CourseMembership is the predicate function for coursemembership builders.
type CourseMembership func(*sql.Selector)

// RefreshSession is the predicate function for refreshsession builders.
type RefreshSession func(*sql.Selector)

// TeacherInvitation is the predicate function for teacherinvitation builders.
type TeacherInvitation func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
